// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.1 (220711a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/lohrfink/lfet-junit5-extension/src/test/resources/Kaffeevollautomat_LF2_using_ti_group_V10.lfet"
// 12.07.2022 00:23
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.2.1 (220711a) build in default

package de.lohrfink.junit5.extension.example;

interface Kaffeevollautomat_LF2_using_ti_group_V10DT<T>
{
 
    // Prolog Standard <----
    
    /** 
     * <b>B02: Getränk ausgewählt?</b><br>
     * <br>
     * <b>B02/01: J - Ja</b>
     */
    public boolean isGetraenkAusgewaehlt(T model);
    
    /** 
     * <b>B03: Gewähltes Getränk?</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName;
     */
    public boolean isGewaehltesGetraenk(Kaffeevollautomat_LF2_using_ti_group_V10DT.GewaehltesGetraenk arg0, T model);
    
    /** 
     * <b>B04: Taste Zubereitung gedrückt?</b><br>
     * <br>
     * <b>B04/01: J - Ja</b>
     */
    public boolean isTasteZubereitungGedrueckt(T model);
    
    /** 
     * <b>B05: Taste Zucker gedückt?</b><br>
     * <br>
     * <b>B05/01: J - Ja</b>
     */
    public boolean isTasteZuckerGedueckt(T model);
    
    /** 
     * <b>B06: Taste Milch gedrückt?</b><br>
     * <br>
     * <b>B06/01: J - Ja</b>
     */
    public boolean isTasteMilchGedrueckt(T model);
    
    /** 
     * <b>B07: Zubereitung abgebrochen?</b><br>
     * <br>
     * <b>B07/01: J - Ja</b>
     */
    public boolean isZubereitungAbgebrochen(T model);
    
    /** 
     * <b>B08: Zubereitung beendet?</b><br>
     * <br>
     * <b>B08/01: J - Ja</b>
     */
    public boolean isZubereitungBeendet(T model);
    
    /** 
     * <b>A01: Taste Zucker aktiv (wählbar)</b><br>
     * <br>
     * <b>A01/01: 0 - nicht aktiv</b>
     */
    public void doTasteZuckerAktivWaehlbar_0(T model);
    
    /** 
     * <b>A01: Taste Zucker aktiv (wählbar)</b><br>
     * <br>
     * <b>A01/02: 1 - aktiv</b>
     */
    public void doTasteZuckerAktivWaehlbar_1(T model);
    
    /** 
     * <b>A02: Taste Milch aktiv (wählbar)</b><br>
     * <br>
     * <b>A02/01: 0 - nicht aktiv</b>
     */
    public void doTasteMilchAktivWaehlbar_0(T model);
    
    /** 
     * <b>A02: Taste Milch aktiv (wählbar)</b><br>
     * <br>
     * <b>A02/02: 1 - aktiv</b>
     */
    public void doTasteMilchAktivWaehlbar_1(T model);
    
    /** 
     * <b>A03: Taste Zubereitung aktiv (wählbar)</b><br>
     * <br>
     * <b>A03/01: 0 - nicht aktiv</b>
     */
    public void doTasteZubereitungAktivWaehlbar_0(T model);
    
    /** 
     * <b>A03: Taste Zubereitung aktiv (wählbar)</b><br>
     * <br>
     * <b>A03/02: 1 - aktiv</b>
     */
    public void doTasteZubereitungAktivWaehlbar_1(T model);
    
    /** 
     * <b>A04: Getränk zubereiten</b><br>
     * <br>
     * <b>A04/01: X - Aktion ausführen</b>
     */
    public void doGetraenkZubereiten(T model);
    
    /** 
     * <b>A05: Zubereitung beenden</b><br>
     * <br>
     * <b>A05/01: X - Aktion ausführen</b>
     */
    public void doZubereitungBeenden(T model);
    
    public void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>B03: Gewähltes Getränk?</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName;
     */
    enum GewaehltesGetraenk
    {
        /** 
         * <b>B03: Gewähltes Getränk?</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>B03/01: Kaf - Cafe Crema</b>
         */
        $001("Kaf", "Cafe Crema"),
        
        /** 
         * <b>B03: Gewähltes Getränk?</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>B03/02: Cap - Cappucino</b>
         */
        $002("Cap", "Cappucino"),
        
        /** 
         * <b>B03: Gewähltes Getränk?</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>B03/03: Mac - Latte Macciato</b>
         */
        $003("Mac", "Latte Macciato");
        
        private final String symbol;
        
        private final String title;
        
        GewaehltesGetraenk(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.2.1 (220711a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.1 (220711a), https://www.lohrfink.de/lfet

