// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.1 (220711a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/lohrfink/lfet-junit5-extension/src/test/resources/Kaffeevollautomat_LF2_using_ti_group_V10.lfet"
// 12.07.2022 00:23
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.1 (220711a) build in default

package de.lohrfink.junit5.extension.example;

public final class Kaffeevollautomat_LF2_using_ti_group_V10DTLogic
{
    public final <T> void execute(Kaffeevollautomat_LF2_using_ti_group_V10DT<T> iface, T model)
    {
 
    // Prolog Standard <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isGetraenkAusgewaehlt(model) )
                {
                    if ( iface.isGewaehltesGetraenk(Kaffeevollautomat_LF2_using_ti_group_V10DT.GewaehltesGetraenk.$001 /* Kaf */ , model) )
                    {
                        // Rule R01 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 1, model);
                        
                        iface.doTasteZuckerAktivWaehlbar_1(model);
                        iface.doTasteMilchAktivWaehlbar_1(model);
                        iface.doTasteZubereitungAktivWaehlbar_1(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R01 <----
                    }
                    else if ( iface.isGewaehltesGetraenk(Kaffeevollautomat_LF2_using_ti_group_V10DT.GewaehltesGetraenk.$002 /* Cap */ , model) )
                    {
                        // Rule R02 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 2, model);
                        
                        iface.doTasteZuckerAktivWaehlbar_1(model);
                        iface.doTasteMilchAktivWaehlbar_0(model);
                        iface.doTasteZubereitungAktivWaehlbar_1(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R02 <----
                    }
                    else if ( iface.isGewaehltesGetraenk(Kaffeevollautomat_LF2_using_ti_group_V10DT.GewaehltesGetraenk.$003 /* Mac */ , model) )
                    {
                        // Rule R03 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 3, model);
                        
                        iface.doTasteZuckerAktivWaehlbar_1(model);
                        iface.doTasteMilchAktivWaehlbar_0(model);
                        iface.doTasteZubereitungAktivWaehlbar_1(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R03 <----
                    }
                    else
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 4, model);
                        
                        iface.doTasteZuckerAktivWaehlbar_0(model);
                        iface.doTasteMilchAktivWaehlbar_0(model);
                        iface.doTasteZubereitungAktivWaehlbar_1(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R04 <----
                    }
                }
                else
                {
                    // Rule R05 ---->
                    
                    iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 5, model);
                    
                    iface.doTasteZuckerAktivWaehlbar_0(model);
                    iface.doTasteMilchAktivWaehlbar_0(model);
                    iface.doTasteZubereitungAktivWaehlbar_0(model);
                    
                    ruleGroup = 1;
                    exit = false;
                    
                    // Rule R05 <----
                }
            }
            else if ( ruleGroup == 2 )
            {
                if ( iface.isTasteZubereitungGedrueckt(model) )
                {
                    // Rule R06 ---->
                    
                    iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 6, model);
                    
                    iface.doTasteZuckerAktivWaehlbar_0(model);
                    iface.doTasteMilchAktivWaehlbar_0(model);
                    iface.doTasteZubereitungAktivWaehlbar_0(model);
                    iface.doGetraenkZubereiten(model);
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R06 <----
                }
                else
                {
                    if ( iface.isTasteZuckerGedueckt(model) )
                    {
                        // Rule R07 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 7, model);
                        
                        iface.doTasteZuckerAktivWaehlbar_0(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R07 <----
                    }
                    else
                    {
                        if ( iface.isTasteMilchGedrueckt(model) )
                        {
                            // Rule R08 ---->
                            
                            iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 8, model);
                            
                            iface.doTasteMilchAktivWaehlbar_0(model);
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            // Rule R08 <----
                        }
                        else
                        {
                            // Rule R09 ---->
                            
                            iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 9, model);
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            // Rule R09 <----
                        }
                    }
                }
            }
            else
            {
                if ( iface.isZubereitungAbgebrochen(model) )
                {
                    // Rule R10 ---->
                    
                    iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 10, model);
                    
                    iface.doZubereitungBeenden(model);
                    
                    exit = true;
                    
                    // Rule R10 <----
                }
                else
                {
                    if ( iface.isZubereitungBeendet(model) )
                    {
                        // Rule R11 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 11, model);
                        
                        iface.doZubereitungBeenden(model);
                        
                        exit = true;
                        
                        // Rule R11 <----
                    }
                    else
                    {
                        // Rule R12 ---->
                        
                        iface.doTrace("Kaffeevollautomat_LF2_using_ti_group_V10", "20220712.002316", 12, 12, model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R12 <----
                    }
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.1 (220711a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.1 (220711a), https://www.lohrfink.de/lfet

