name: release version

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: build and test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"
          git-release-bot-name: "bot-uniqueck"
          git-release-bot-email: "bot@uniqueck.io"