name: release version

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "bot-uniqueck"
          git-release-bot-email: "bot@uniqueck.io"

          release-branch-name: "main"

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
          maven-servers: '[{"id": "serverId1", "username": "username", "password": "password", "privateKey": "test", "passphrase": "testes"}, {"id": "serverId2", "username": "username2", "password": "password2"}]'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
